Event.create(title: 'Go to bed', descript: "I'm sleepy", date: 19900530, creator_id: 1)
Event.create(title: 'Go to work', descript: "I'm ready", date: 20200416, creator_id: 2)
User.create(user: 'TheStig', name:'Stig McMan', email: 'stig@yahoo.com')
User.create(user: 'StigJr', name:'Stig McMan Jr.', email: 'stigjr@yahoo.com')
Invite.create(attended_event_id: 1, attendee_id: 2)
Invite.create(attended_event_id: 2, attendee_id: 1)
